// shots.mjs — le découpage visuel de « Alan Turing : l'histoire complète »
//
// Une entrée par phrase de story.json (même ordre) :
//   un plan, un tableau de plans (ils se partagent la phrase, poids « w »), ou null
//   (la phrase garde le plan précédent).
// Les choix suivent les sections « Visuels » et « Montage » du script Notion (V06) :
// nouveau visuel toutes les 2-4 s, Ken Burns vers le sujet, étalonnage par époque,
// pas de fausse archive (documents recomposés marqués « illustration »).

// Étalonnage par époque (tools/grades.json, presets HyperFrames) :
//   sepia (1912-1939) · guerre (1939-1945, N&B contrasté) · froid (1945-1954) · rien (2009-2021)
const P = (src, o = {}) => ({ t: "photo", src, ...o });
const C = (text, o = {}) => ({ t: "card", text, ...o });
const D = (text, o = {}) => ({ t: "date", text, ...o });
const CH = (n, title) => ({ t: "chapter", n, title, w: 0.9 });

// Positions de la carte schématique (px, 1920×1080) — pas une carte géographique exacte
const MAP = {
  londres: ["Londres", 700, 330], inde: ["Inde", 1500, 700], sherborne: ["Sherborne", 560, 420],
  cambridge: ["Cambridge", 820, 300], princeton: ["Princeton", 250, 420],
  varsovie: ["Varsovie (Pyry)", 1300, 330], paris: ["Paris", 780, 520], bletchley: ["Bletchley Park", 720, 260],
};

export const CREDITS = {
  "turing-1951.jpg": "Elliott & Fry, 1951 · domaine public",
  "turing-16-ans.jpg": "v. 1928 · domaine public",
  "turing-1930s.jpg": "Années 1930 · domaine public",
  "londres-parlement.jpg": "Photochrome v. 1900 · Library of Congress",
  "memorial-manchester.jpg": "S. Harriyott · CC BY 2.0",
  "kings-college.jpg": "D. Tonkonog · CC BY-SA 3.0",
  "enigma-guderian-1940.jpg": "Bundesarchiv 101I-769-0229-10A / E. Borchert · CC BY-SA 3.0 DE",
  "enigma-reglages.jpg": "Luftwaffe, v. 1944 · domaine public",
  "bletchley-park.jpg": "DeFacto · CC BY-SA 4.0",
  "bombe.jpg": "Bombe reconstruite · TedColes · CC0",
  "enigma-1943.jpg": "Bundesarchiv 183-2007-0705-502 / Walther · CC BY-SA 3.0 DE",
  "pilot-ace.jpg": "Pilot ACE · A. Taveneaux · CC BY-SA 3.0",
  "maison-wilmslow.jpg": "Dunk · CC BY 4.0",
  "statue-manchester.jpg": "Mémorial de Manchester · KGGucwa · domaine public",
  "sherborne-1907.jpg": "Sherborne, 1907 · Fuseemusee · CC BY-SA 4.0",
  "sherborne-ecole.jpg": "SophieHarris-Sherborne · CC BY-SA 4.0",
  "rejewski.jpg": "Marian Rejewski, v. 1943 · domaine public",
  "feuille-zygalski.jpg": "Feuille de Zygalski · domaine public",
  "enigma-rotors-anneaux.jpg": "Rotors d'Enigma · TedColes · CC0",
  "monument-poznan.jpg": "Monument aux cryptologues polonais · Pnapora · CC BY-SA 3.0",
  "hut8.jpg": "Ian Petticrew · CC BY-SA 2.0",
  "ferranti-1951.jpg": "Ferranti Mark 1, 1951 · Science Museum Group · CC BY-SA 4.0",
  "gordon-brown.jpg": "Gouvernement britannique · OGL v1.0",
  "reine-brown-2010.jpg": "Number 10 · CC BY 2.0",
  "convoi-1942.jpg": "US Navy 80-G-72409 · domaine public",
  "guetteur-1942.jpg": "Royal Navy, IWM A13362 · domaine public",
  "pomme.jpg": "D. Wilson / USDA · domaine public",
  "ciel-etoile.jpg": "ESO / S. Brunier · CC BY 4.0",
};

// Portrait (photo verticale) : cadre centré au lieu du plein écran
const portrait = { fit: "contain" };

export const SHOTS = {
  "00-hook": [
    // Premier frame = portrait + « 1952 : condamné » (sert de miniature)
    [P("turing-16-ans.jpg", { ...portrait, label: "1952 : condamné", instant: true, focus: [50, 30], w: 2.2 }),
     { t: "doc", lines: ["Royaume-Uni · 31 mars 1952", "Affaire : Alan M. Turing", "Chef d'accusation : « grossière indécence »"], w: 1 }],
    C("Son [crime] ?"),
    C("Avoir aimé [un homme].", { punch: 0.5 }),
  ],
  "01-enjeux": [
    P("statue-manchester.jpg", { ...portrait, label: "1952 → 2013 : 61 ans", focus: [50, 30] }),
    [P("bombe.jpg", { era: "guerre", focus: [50, 50] }), P("enigma-rotors-anneaux.jpg", { era: "guerre", focus: [50, 50] }), P("pomme.jpg", { focus: [50, 50], zoom: [1.1, 1.25] })],
    P("turing-1951.jpg", { ...portrait, era: "froid", label: "Alan Turing", focus: [50, 35] }),
  ],
  "02-boucle": [
    C("Tu connais peut-être [le film].", { kicker: "The Imitation Game, 2014" }),
    P("enigma-1943.jpg", { era: "guerre", focus: [55, 45] }),
    P("enigma-rotors-anneaux.jpg", { era: "guerre", label: "L'histoire complète", focus: [50, 50], zoom: [1.25, 1.05] }),
    C("Et plus [dure].", { dark: true }),
    P("turing-16-ans.jpg", { ...portrait, era: "sepia", focus: [50, 35], zoom: [1.0, 1.12] }),
    P("pomme.jpg", { label: "La pomme : on y reviendra", focus: [50, 50], zoom: [1.15, 1.3] }),
    C("Personne n'est d'accord sur ce qu'elle [veut dire]."),
  ],
  "03-christopher": [
    [CH(1, "Christopher"), P("londres-parlement.jpg", { era: "sepia", label: "Londres, 23 juin 1912", focus: [60, 40], w: 1.2 })],
    P("memorial-manchester.jpg", { label: "Sa maison natale, Maida Vale", focus: [50, 45] }),
    { t: "map", title: "Son père travaille en Inde", points: [MAP.londres, MAP.inde] },
    P("londres-parlement.jpg", { era: "sepia", focus: [20, 60], zoom: [1.25, 1.1] }),
    C("Passionné de [chiffres] et de [chimie]."),
    P("sherborne-ecole.jpg", { label: "Sherborne", focus: [50, 40] }),
    P("sherborne-1907.jpg", { era: "sepia", focus: [50, 50] }),
    C("Il « perd son temps » dans une école [comme la leur].", { note: "D'après un rapport de son directeur" }),
    P("turing-16-ans.jpg", { ...portrait, era: "sepia", focus: [50, 35], zoom: [1.05, 1.18] }),
    C("Christopher [Morcom]", { kicker: "1911 – 1930" }),
    P("ciel-etoile.jpg", { label: "Passionné d'astronomie", focus: [50, 50], zoom: [1.0, 1.2] }),
    P("sherborne-1907.jpg", { era: "sepia", focus: [30, 40], zoom: [1.3, 1.15] }),
    null,
    P("turing-16-ans.jpg", { ...portrait, era: "sepia", focus: [50, 30], zoom: [1.1, 1.25] }),
    D("13 février 1930", { sub: "Christopher meurt de la tuberculose", punch: 0.3 }),
    null,
    P("turing-16-ans.jpg", { ...portrait, era: "sepia", focus: [55, 32], zoom: [1.25, 1.35] }),
    C("Qu'est-ce qu'un [esprit] ?", { dark: true }),
    P("ciel-etoile.jpg", { focus: [40, 60], zoom: [1.15, 1.35] }),
    C("Qu'est-ce qu'un [esprit] ?", { dark: true, note: "Garde cette question en tête" }),
    null,
  ],
  "04-machine": [
    [CH(2, "La machine imaginaire"), P("kings-college.jpg", { label: "Cambridge, 1931", focus: [50, 40], w: 1.3 })],
    P("turing-1930s.jpg", { ...portrait, era: "sepia", focus: [50, 30] }),
    P("kings-college.jpg", { label: "Membre du collège à 22 ans", focus: [30, 30], zoom: [1.25, 1.1] }),
    { t: "doc", lines: ["On Computable Numbers", "A. M. Turing — 1936", "Proceedings of the London Mathematical Society", "« Sur les nombres calculables »"] },
    C("Une idée [folle]."),
    { t: "tape", title: "La machine de Turing · 1936", hold: true },
    null,
    null,
    null,
    C("C'est [tout]."),
    [P("turing-1930s.jpg", { ...portrait, era: "sepia", focus: [50, 28], zoom: [1.15, 1.3] }), { t: "tape", title: "Une machine pour imiter toutes les autres" }],
    C("Une machine [universelle].", { punch: 0.4 }),
    null,
    C("C'est l'idée de [l'ordinateur]."),
    C("Un appareil. Des [programmes] différents."),
    P("ferranti-1951.jpg", { era: "froid", label: "Ordinateurs à programme enregistré : 1948", focus: [50, 45] }),
    { t: "map", title: "1936 – 1938", points: [MAP.cambridge, MAP.princeton] },
    P("turing-1930s.jpg", { ...portrait, era: "sepia", label: "Princeton · doctorat avec Alonzo Church", focus: [50, 40] }),
    D("1938", { sub: "Retour en Angleterre" }),
    null,
  ],
  "05-bletchley": [
    [CH(3, "Bletchley Park et Enigma"), D("Septembre 1939", { w: 1.1 })],
    P("enigma-guderian-1940.jpg", { ...portrait, era: "guerre", focus: [50, 45] }),
    P("bletchley-park.jpg", { era: "guerre", label: "Bletchley Park", focus: [45, 45] }),
    P("hut8.jpg", { era: "guerre", focus: [50, 50] }),
    P("enigma-1943.jpg", { era: "guerre", label: "Enigma", focus: [55, 40] }),
    P("enigma-guderian-1940.jpg", { ...portrait, era: "guerre", focus: [40, 75], zoom: [1.2, 1.4] }),
    [P("enigma-rotors-anneaux.jpg", { era: "guerre", focus: [40, 55] }), P("enigma-reglages.jpg", { era: "guerre", focus: [40, 40] })],
    { t: "counter", to: "159 000 000 000 000 000 000", kicker: "Réglages possibles", label: "des milliards de milliards" },
    C("Mais il faut rendre [justice] à quelqu'un."),
    C("Les premiers ? Pas les [Britanniques]."),
    P("rejewski.jpg", { ...portrait, era: "guerre", label: "Marian Rejewski · Pologne", focus: [50, 35] }),
    [{ t: "map", title: "Juillet 1939", points: [MAP.varsovie, MAP.paris, MAP.londres], w: 1.3 }, P("monument-poznan.jpg", { ...portrait, focus: [50, 40] })],
    P("feuille-zygalski.jpg", { ...portrait, era: "guerre", focus: [50, 50] }),
    P("bombe.jpg", { era: "guerre", label: "La Bombe", focus: [45, 40] }),
    { t: "bombe", kicker: "La Bombe · schéma" },
    D("Mars 1940", { sub: "La première Bombe est installée" }),
    P("hut8.jpg", { era: "guerre", label: "Hut 8 · marine allemande", focus: [40, 55], zoom: [1.2, 1.05] }),
    C("Le plus [dur] de tous."),
    P("guetteur-1942.jpg", { era: "guerre", focus: [45, 40] }),
    P("convoi-1942.jpg", { era: "guerre", label: "Convois de l'Atlantique", focus: [50, 50] }),
    { t: "enigma", word: "UBOOT", label: "1941" },
    C("Ils manquent de [tout]."),
    P("bletchley-park.jpg", { era: "guerre", focus: [70, 50], zoom: [1.3, 1.15] }),
    P("bombe.jpg", { era: "guerre", focus: [70, 70], zoom: [1.35, 1.5] }),
    D("Octobre 1941"),
    C("Winston [Churchill]", { kicker: "Premier ministre" }),
    null,
    { t: "doc", lines: ["Lettre à Winston Churchill", "21 octobre 1941", "Turing · Welchman · Alexander · Milner-Barry"], stamp: "Action this day", stampAt: 1.6 },
    P("bombe.jpg", { era: "guerre", focus: [30, 30], zoom: [1.1, 1.25] }),
    C("Combien de [vies] ?"),
    null,
    C("Jusqu'à [2 ans] de guerre en moins", { note: "Selon Bletchley Park — estimation débattue" }),
    null,
    P("bletchley-park.jpg", { era: "guerre", focus: [50, 30], zoom: [1.05, 1.2] }),
    C("Classé [secret].", { punch: 0.3 }),
  ],
  "06-penser": [
    [CH(4, "Une machine peut-elle penser ?"), P("turing-1951.jpg", { ...portrait, era: "froid", label: "Décoré de l'OBE", focus: [50, 35], w: 1.2 })],
    null,
    { t: "tape", title: "Sa machine universelle… pour de vrai" },
    P("pilot-ace.jpg", { era: "froid", label: "ACE · Laboratoire national de physique", focus: [50, 50] }),
    P("ferranti-1951.jpg", { era: "froid", label: "Manchester, 1948", focus: [40, 50] }),
    P("ferranti-1951.jpg", { era: "froid", focus: [70, 40], zoom: [1.3, 1.15] }),
    [D("1950", { w: 0.6 }), C("Les machines peuvent-elles [penser] ?")],
    C("Il propose un [jeu]."),
    { t: "chat", hold: true },
    null,
    C("Le test de [Turing]."),
    P("ciel-etoile.jpg", { focus: [60, 40], zoom: [1.2, 1.05] }),
    C("Qu'est-ce qu'un [esprit] ?", { dark: true, note: "1930 → 1950" }),
    C("1951 : la [Royal Society]", { kicker: "L'une des plus prestigieuses académies scientifiques" }),
    P("turing-1951.jpg", { ...portrait, era: "froid", focus: [50, 30], zoom: [1.1, 1.25] }),
    null,
  ],
  "07-proces": [
    [CH(5, "Le procès"), D("Janvier 1952", { w: 1.1 })],
    P("maison-wilmslow.jpg", { era: "froid", label: "Wilmslow, près de Manchester", focus: [50, 40] }),
    C("Il porte [plainte]."),
    [P("turing-1951.jpg", { ...portrait, era: "froid", focus: [50, 35] }), P("maison-wilmslow.jpg", { era: "froid", focus: [40, 60], zoom: [1.3, 1.15] })],
    C("Il ne cache [rien]."),
    null,
    C("L'homosexualité masculine est un [crime].", { note: "Royaume-Uni, 1952" }),
    C("La victime devient [l'accusé].", { dark: true }),
    { t: "doc", lines: ["Royaume-Uni · 31 mars 1952", "Alan Mathison Turing", "« Grossière indécence »"], stamp: "Coupable", stampAt: 2.2 },
    C("Un [choix]."),
    C("La [prison]."),
    C("Ou un traitement [hormonal].", { note: "Un an de mise à l'épreuve" }),
    null,
    P("turing-1951.jpg", { ...portrait, era: "froid", focus: [50, 30], zoom: [1.2, 1.05] }),
    null,
    C("Habilitation [retirée]."),
    P("bletchley-park.jpg", { era: "froid", focus: [50, 45] }),
    C("Guerre froide : un « [risque] ».", { dark: true }),
  ],
  // Chapitre 6 : sobre — fondus lents, pas d'effet choc
  "08-pomme": [
    [CH(6, "La pomme"), P("maison-wilmslow.jpg", { era: "froid", label: "7 juin 1954", focus: [50, 40], fade: 0.8, w: 1.2 })],
    C("Il avait [41 ans].", { dark: true, fade: 0.6 }),
    P("pomme.jpg", { focus: [50, 50], zoom: [1.1, 1.2], fade: 0.8 }),
    null,
    C("Enquête de 1954 : [suicide].", { fade: 0.6 }),
    null,
    P("turing-1951.jpg", { ...portrait, era: "froid", focus: [50, 35], fade: 0.8 }),
    C("Sa mère : un [accident].", { fade: 0.6 }),
    P("maison-wilmslow.jpg", { era: "froid", focus: [65, 55], zoom: [1.25, 1.35], fade: 0.8 }),
    P("pomme.jpg", { label: "Pomme jamais analysée", focus: [50, 50], zoom: [1.2, 1.3], fade: 0.8 }),
    C("Jack Copeland : accident [possible].", { note: "Historien, spécialiste de Turing", fade: 0.6 }),
    null,
    P("turing-1951.jpg", { ...portrait, era: "froid", focus: [50, 30], zoom: [1.0, 1.12], fade: 0.8 }),
  ],
  "09-reparation": [
    [CH(7, "La réparation"), P("statue-manchester.jpg", { ...portrait, focus: [50, 35], w: 1.2 })],
    P("gordon-brown.jpg", { ...portrait, label: "2009 : excuses officielles", focus: [50, 30] }),
    [D("24 décembre 2013", { sub: "Pardon royal" }), P("reine-brown-2010.jpg", { label: "Élisabeth II", focus: [50, 40] })],
    C("[61 ans] après sa condamnation."),
    { t: "timeline", items: [["2009", "Excuses du gouvernement"], ["2013", "Pardon royal"], ["2017", "« Loi Alan Turing »"], ["2021", "Billet de 50 £"]], at: [0.2, 0.6, 1.0, 1.4] },
    [D("23 juin 2021", { sub: "Le jour de son anniversaire", w: 0.8 }), { t: "note50" }],
    null,
  ],
  "10-fin": [
    { t: "tape", title: "1936" },
    P("bombe.jpg", { era: "guerre", focus: [50, 50], zoom: [1.2, 1.05] }),
    { t: "chat" },
    { t: "note50" },
    null,
    // Dernier frame = premier frame (boucle)
    P("turing-16-ans.jpg", { ...portrait, label: "1952 : condamné", instant: true, focus: [50, 30], hold: true }),
  ],
};
